apiVersion: apps/v1
kind: Deployment
metdata:
  name: worker-app-deployment
  labels:
    app: worker-app

spec:
  replicas: 1
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
